"""Add ulixe_ids to campaigns and update user roles

Revision ID: 01538fb04cf3
Revises: ee21c6533976
Create Date: 2026-01-12 18:01:38.868156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01538fb04cf3'
down_revision: Union[str, None] = 'ee21c6533976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Verifica se la tabella managed_campaigns esiste
    # Se non esiste, questa migration viene saltata (la tabella verrà creata in una migration successiva)
    # Se esiste, aggiungi la colonna ulixe_ids
    from sqlalchemy import inspect
    
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'managed_campaigns' in tables:
        # La tabella esiste, aggiungi la colonna
        try:
            # Verifica se la colonna esiste già
            columns = [col['name'] for col in inspector.get_columns('managed_campaigns')]
            if 'ulixe_ids' not in columns:
                op.add_column('managed_campaigns', sa.Column('ulixe_ids', sa.JSON(), nullable=True))
        except Exception:
            # Errore durante l'aggiunta, ignora (probabilmente colonna già esistente)
            pass
    # Se la tabella non esiste, non fare nulla (verrà creata in add_payout_hierarchy)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managed_campaigns', 'ulixe_ids')
    # ### end Alembic commands ###
