"""Add form_id to lead

Revision ID: 1d723402bf5e
Revises: 72f888a504f9
Create Date: 2026-01-12 19:54:26.404238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d723402bf5e'
down_revision: Union[str, None] = '72f888a504f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('form_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'form_id')
    # ### end Alembic commands ###
