"""Add ulixe_ids to campaigns and update user roles

Revision ID: 01538fb04cf3
Revises: ee21c6533976
Create Date: 2026-01-12 18:01:38.868156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01538fb04cf3'
down_revision: Union[str, None] = 'ee21c6533976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_campaigns', sa.Column('ulixe_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managed_campaigns', 'ulixe_ids')
    # ### end Alembic commands ###
