"""Expand Lead model fields

Revision ID: 72f888a504f9
Revises: 01538fb04cf3
Create Date: 2026-01-12 18:16:57.024500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f888a504f9'
down_revision: Union[str, None] = '01538fb04cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('external_user_id', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('city', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('region', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('msg_id', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('source', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('campaign_name', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('magellano_campaign_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_leads_user_id'), table_name='leads')
    op.create_index(op.f('ix_leads_external_user_id'), 'leads', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_leads_magellano_campaign_id'), 'leads', ['magellano_campaign_id'], unique=False)
    op.drop_column('leads', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_leads_magellano_campaign_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_external_user_id'), table_name='leads')
    op.create_index(op.f('ix_leads_user_id'), 'leads', ['user_id'], unique=True)
    op.drop_column('leads', 'magellano_campaign_id')
    op.drop_column('leads', 'campaign_name')
    op.drop_column('leads', 'source')
    op.drop_column('leads', 'msg_id')
    op.drop_column('leads', 'brand')
    op.drop_column('leads', 'region')
    op.drop_column('leads', 'city')
    op.drop_column('leads', 'external_user_id')
    # ### end Alembic commands ###
