"""Initial clean migration

Revision ID: ad3361661c7c
Revises: 
Create Date: 2026-01-16 11:37:18.383809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3361661c7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('on_success', sa.Boolean(), nullable=True),
    sa.Column('on_error', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_configs_alert_type'), 'alert_configs', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alert_configs_id'), 'alert_configs', ['id'], unique=False)
    op.create_table('cron_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.Column('day_of_month', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cron_jobs_id'), 'cron_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_cron_jobs_job_name'), 'cron_jobs', ['job_name'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magellano_id', sa.String(), nullable=True),
    sa.Column('external_user_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('msg_id', sa.String(), nullable=True),
    sa.Column('form_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.Column('magellano_campaign_id', sa.String(), nullable=True),
    sa.Column('payout_status', sa.String(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('facebook_ad_name', sa.String(), nullable=True),
    sa.Column('facebook_ad_set', sa.String(), nullable=True),
    sa.Column('facebook_campaign_name', sa.String(), nullable=True),
    sa.Column('facebook_id', sa.String(), nullable=True),
    sa.Column('facebook_piattaforma', sa.String(), nullable=True),
    sa.Column('meta_campaign_id', sa.String(), nullable=True),
    sa.Column('meta_adset_id', sa.String(), nullable=True),
    sa.Column('meta_ad_id', sa.String(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.Column('status_category', sa.Enum('IN_LAVORAZIONE', 'RIFIUTATO', 'CRM', 'FINALE', 'UNKNOWN', name='statuscategory'), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('to_sync_meta', sa.Boolean(), nullable=True),
    sa.Column('last_meta_event_status', sa.String(), nullable=True),
    sa.Column('meta_correlation_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_external_user_id'), 'leads', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_leads_facebook_ad_name'), 'leads', ['facebook_ad_name'], unique=False)
    op.create_index(op.f('ix_leads_facebook_ad_set'), 'leads', ['facebook_ad_set'], unique=False)
    op.create_index(op.f('ix_leads_facebook_campaign_name'), 'leads', ['facebook_campaign_name'], unique=False)
    op.create_index(op.f('ix_leads_facebook_id'), 'leads', ['facebook_id'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_magellano_campaign_id'), 'leads', ['magellano_campaign_id'], unique=False)
    op.create_index(op.f('ix_leads_magellano_id'), 'leads', ['magellano_id'], unique=True)
    op.create_index(op.f('ix_leads_meta_ad_id'), 'leads', ['meta_ad_id'], unique=False)
    op.create_index(op.f('ix_leads_meta_adset_id'), 'leads', ['meta_adset_id'], unique=False)
    op.create_index(op.f('ix_leads_meta_campaign_id'), 'leads', ['meta_campaign_id'], unique=False)
    op.create_index(op.f('ix_leads_msg_id'), 'leads', ['msg_id'], unique=False)
    op.create_index(op.f('ix_leads_to_sync_meta'), 'leads', ['to_sync_meta'], unique=False)
    op.create_table('managed_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('magellano_ids', sa.JSON(), nullable=True),
    sa.Column('msg_ids', sa.JSON(), nullable=True),
    sa.Column('pay_level', sa.String(), nullable=True),
    sa.Column('ulixe_ids', sa.JSON(), nullable=True),
    sa.Column('meta_dataset_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managed_campaigns_cliente_name'), 'managed_campaigns', ['cliente_name'], unique=True)
    op.create_index(op.f('ix_managed_campaigns_id'), 'managed_campaigns', ['id'], unique=False)
    op.create_table('smtp_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('from_email', sa.String(), nullable=True),
    sa.Column('use_tls', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smtp_configs_id'), 'smtp_configs', ['id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_id'), 'sync_logs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('id_sede', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('lead_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_category', sa.Enum('IN_LAVORAZIONE', 'RIFIUTATO', 'CRM', 'FINALE', 'UNKNOWN', name='statuscategory'), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_history_id'), 'lead_history', ['id'], unique=False)
    op.create_table('meta_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('sync_frequency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'user_id', name='uq_meta_account_user')
    )
    op.create_index(op.f('ix_meta_accounts_account_id'), 'meta_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_meta_accounts_id'), 'meta_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_meta_accounts_user_id'), 'meta_accounts', ['user_id'], unique=False)
    op.create_table('meta_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('daily_budget', sa.String(), nullable=True),
    sa.Column('lifetime_budget', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('sync_filters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['meta_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_campaigns_campaign_id'), 'meta_campaigns', ['campaign_id'], unique=True)
    op.create_index(op.f('ix_meta_campaigns_id'), 'meta_campaigns', ['id'], unique=False)
    op.create_table('meta_adsets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('adset_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('optimization_goal', sa.String(), nullable=True),
    sa.Column('targeting', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['meta_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_adsets_adset_id'), 'meta_adsets', ['adset_id'], unique=True)
    op.create_index(op.f('ix_meta_adsets_id'), 'meta_adsets', ['id'], unique=False)
    op.create_table('meta_ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adset_id', sa.Integer(), nullable=True),
    sa.Column('ad_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('creative_id', sa.String(), nullable=True),
    sa.Column('creative_thumbnail_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adset_id'], ['meta_adsets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_ads_ad_id'), 'meta_ads', ['ad_id'], unique=True)
    op.create_index(op.f('ix_meta_ads_id'), 'meta_ads', ['id'], unique=False)
    op.create_table('meta_marketing_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('ad_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('spend', sa.String(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.String(), nullable=True),
    sa.Column('cpc', sa.String(), nullable=True),
    sa.Column('cpm', sa.String(), nullable=True),
    sa.Column('cpa', sa.String(), nullable=True),
    sa.Column('additional_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['meta_ads.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_marketing_data_date'), 'meta_marketing_data', ['date'], unique=False)
    op.create_index(op.f('ix_meta_marketing_data_id'), 'meta_marketing_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_marketing_data_id'), table_name='meta_marketing_data')
    op.drop_index(op.f('ix_meta_marketing_data_date'), table_name='meta_marketing_data')
    op.drop_table('meta_marketing_data')
    op.drop_index(op.f('ix_meta_ads_id'), table_name='meta_ads')
    op.drop_index(op.f('ix_meta_ads_ad_id'), table_name='meta_ads')
    op.drop_table('meta_ads')
    op.drop_index(op.f('ix_meta_adsets_id'), table_name='meta_adsets')
    op.drop_index(op.f('ix_meta_adsets_adset_id'), table_name='meta_adsets')
    op.drop_table('meta_adsets')
    op.drop_index(op.f('ix_meta_campaigns_id'), table_name='meta_campaigns')
    op.drop_index(op.f('ix_meta_campaigns_campaign_id'), table_name='meta_campaigns')
    op.drop_table('meta_campaigns')
    op.drop_index(op.f('ix_meta_accounts_user_id'), table_name='meta_accounts')
    op.drop_index(op.f('ix_meta_accounts_id'), table_name='meta_accounts')
    op.drop_index(op.f('ix_meta_accounts_account_id'), table_name='meta_accounts')
    op.drop_table('meta_accounts')
    op.drop_index(op.f('ix_lead_history_id'), table_name='lead_history')
    op.drop_table('lead_history')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sync_logs_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_smtp_configs_id'), table_name='smtp_configs')
    op.drop_table('smtp_configs')
    op.drop_index(op.f('ix_managed_campaigns_id'), table_name='managed_campaigns')
    op.drop_index(op.f('ix_managed_campaigns_cliente_name'), table_name='managed_campaigns')
    op.drop_table('managed_campaigns')
    op.drop_index(op.f('ix_leads_to_sync_meta'), table_name='leads')
    op.drop_index(op.f('ix_leads_msg_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_meta_campaign_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_meta_adset_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_meta_ad_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_magellano_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_magellano_campaign_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_facebook_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_facebook_campaign_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_facebook_ad_set'), table_name='leads')
    op.drop_index(op.f('ix_leads_facebook_ad_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_external_user_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_cron_jobs_job_name'), table_name='cron_jobs')
    op.drop_index(op.f('ix_cron_jobs_id'), table_name='cron_jobs')
    op.drop_table('cron_jobs')
    op.drop_index(op.f('ix_alert_configs_id'), table_name='alert_configs')
    op.drop_index(op.f('ix_alert_configs_alert_type'), table_name='alert_configs')
    op.drop_table('alert_configs')
    # ### end Alembic commands ###
