"""Add id_sede to users

Revision ID: b776dff1016a
Revises: e1885186f620
Create Date: 2026-01-12 15:59:51.649839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b776dff1016a'
down_revision: Union[str, None] = 'e1885186f620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_sede', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'id_sede')
    # ### end Alembic commands ###
