"""Add giorgio to whitelist

Revision ID: ee21c6533976
Revises: b776dff1016a
Create Date: 2026-01-12 16:38:51.830200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee21c6533976'
down_revision: Union[str, None] = 'b776dff1016a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO users (email, is_active, role, id_sede) VALUES ('giorgio.contarini@triboo.it', true, 'admin', 'DIRECT') ON CONFLICT (email) DO NOTHING")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE email = 'giorgio.contarini@triboo.it'")
    # ### end Alembic commands ###
